apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: podlimit-master
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""
  kubeletConfig:
    maxPods: 500
