apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: podlimit-worker
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  kubeletConfig:
    maxPods: 500
    cpuCfsQuota: false
