apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: rhacs
spec:
  network:
    policies: Enabled
  central:
    adminPasswordGenerationDisabled: false
    declarativeConfiguration:
      configMaps:
        - name: declarative-configurations
    exposure:
      route:
        enabled: true
        host: "acs.${SUB_DOMAIN}"
    defaultTLSSecret:
      name: rhacs-central-tls-cert
    telemetry:
      enabled: false
    db:
      isEnabled: Default
      resources:
        requests:
          cpu: "0"
      persistence:
        persistentVolumeClaim:
          claimName: central-db
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  scanner:
    db:
      resources:
        requests:
          cpu: "0"
    analyzer:
      scaling:
        autoScaling: Disabled
        replicas: 1
      resources:
        requests:
          cpu: "0"
  scannerV4:
    db:
      resources:
        requests:
          cpu: "0"
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
    indexer:
      scaling:
        autoScaling: Disabled
        replicas: 1
      resources:
        requests:
          cpu: "0"
    matcher:
      scaling:
        autoScaling: Disabled
        replicas: 1
      resources:
        requests:
          cpu: "0"
