apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: rhacs
spec:
  network:
    policies: Enabled
  central:
    adminPasswordGenerationDisabled: false
    declarativeConfiguration:
      configMaps:
        - name: declarative-configurations
    exposure:
      route:
        enabled: true
        host: "acs.${SUB_DOMAIN}"
    telemetry:
      enabled: false
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  scanner:
    scannerComponent: Disabled
  scannerV4:
    scannerComponent: Disabled
    db:
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
