apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: central
  namespace: rhacs
spec:
  secretName: rhacs-central-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - acs.apps.${BASE_DOMAIN}
