apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhdh-cert
  namespace: rhdh
spec:
  secretName: rhdh-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "devhub.puiterwijk.org"
  dnsNames:
    - "devhub.puiterwijk.org"
