apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: PUiterwijk Developer Hub
      baseUrl: https://devhub.apps.primary.ocp.puiterwijk.org
    signInPage: oidc
    auth:
      environment: production
      session:
        secret: "${BACKEND_SECRET}"
      providers:
        oidc:
          production:
            metadataUrl: "https://sso.puiterwijk.org/realms/services"
            clientId: "${AUTH_OIDC_CLIENT_ID}"
            clientSecret: "${AUTH_OIDC_CLIENT_SECRET}"
            prompt: auto
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
                - resolver: emailMatchingUserEntityProfileEmail
    dangerouslyAllowSignInWithoutUserInCatalog: true
    catalog:
      providers:
        keycloakOrg:
          default:
            baseUrl: "https://sso.puiterwijk.org"
            realm: services
            loginRealm: services
            clientId: "${AUTH_OIDC_CLIENT_ID}"
            clientSecret: "${AUTH_OIDC_CLIENT_SECRET}"
            schedule:
              frequency: { minutes: 15 }
              initialDelay: { seconds: 15 }
              timeout: { minutes: 2 }
    backend:
      baseUrl: https://devhub.apps.primary.ocp.puiterwijk.org
      cors:
        origin: https://devhub.apps.primary.ocp.puiterwijk.org
    permission:
      enabled: true
      rbac:
        admin:
          users:
            - name: group:default/devhub-admins
