apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh
spec:
  application:
    replicas: 1
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - app-config-rhdh
    extraEnvs:
      secrets:
        - name: secrets-rhdh
    route:
      subdomain: devhub
