apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: config-puiterwijk-general
        - name: config-puiterwijk-catalog
        - name: config-puiterwijk-homepage
        - name: config-puiterwijk-proxy
    dynamicPluginsConfigMapName: plugins-rhdh
    extraEnvs:
      secrets:
        - name: secrets-rhdh
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: rbac-policies
    route:
      enabled: false
  deployment:
    patch:
      spec:
        replicas: 2
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                emptyDir: {}
