apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins-rhdh
  namespace: rhdh
data:
  dynamic-plugins.yaml: |
    plugins:
    - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
      disabled: false
