apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-policies
  namespace: rhdh
data:
  rbac-policies.csv: |
    g, group:default/devhub-admins, role:default/superadmins

    # General stuff
    p, role:default/superadmins, catalog-entity, read, allow
    p, role:default/superadmins, catalog.entity.create, create, allow

    # RBAC admin
    p, role:default/superadmins, policy-entity, read, allow
    # Explicitly no create/delete/update for policy-entity: policies are managed here.
    p, role:default/superadmins, catalog-entity, read, allow
    p, role:default/superadmins, catalog.location.read, read, allow
    p, role:default/superadmins, catalog.location.create, create, allow
    p, role:default/superadmins, catalog.location.delete, delete, allow
    p, role:default/superadmins, scaffolder.task.cancel, use, allow
    p, role:default/superadmins, scaffolder.task.create, create, allow
    p, role:default/superadmins, scaffolder.task.read, read, allow
    p, role:default/superadmins, scaffolder-template, read, allow
    p, role:default/superadmins, scaffolder-action, use, allow
  rbac-conditional-policies.yaml: ""
