apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: developer-hub
  namespace: rhdh
  annotations:
    route.openshift.io/termination: "edge"
spec:
  ingressClassName: openshift-default
  rules:
    - host: devhub.puiterwijk.org
      http:
        paths:
          - backend:
              service:
                name: backstage-developer-hub
                port:
                  name: http-backend
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - devhub.puiterwijk.org
      secretName: rhdh-cert
