apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backstage-developer-hub
  namespace: rhdh
spec:
  path: /
  port:
    targetPort: http-backend
  subdomain: devhub
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backstage-developer-hub
    weight: 100
  wildcardPolicy: None
