apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets-rhdh
  namespace: rhdh
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: secrets-rhdh
    template:
      mergePolicy: Merge
      metadata:
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  data:
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/backend_secret
        property: key
    - secretKey: AUTH_OIDC_CLIENT_ID
      remoteRef:
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/oidc
        property: client_id
    - secretKey: AUTH_OIDC_CLIENT_SECRET
      remoteRef:
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/oidc
        property: client_secret
    - secretKey: GITHUB_APP_ID
      remoteRef:
        metadataPolicy: Fetch
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: app_id
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        metadataPolicy: Fetch
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: client_id
    - secretKey: GITHUB_HOST_DOMAIN
      remoteRef:
        metadataPolicy: Fetch
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: host_domain
    - secretKey: GITHUB_ORGANIZATION
      remoteRef:
        metadataPolicy: Fetch
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: organization
    - secretKey: GITHUB_ORG_URL
      remoteRef:
        metadataPolicy: Fetch
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: organization_url
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: client_secret
    - secretKey: GITHUB_PRIVATE_KEY_FILE
      remoteRef:
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: private_key
    - secretKey: GITHUB_WEBHOOK_SECRET
      remoteRef:
        key: ocp/cluster/${CLUSTER_NAME}/rhdh/github
        property: webhook_secret
