apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repos-gitops-clusters
  namespace: openshift-gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitops
  target:
    name: repos-gitops-clusters
    template:
      mergePolicy: Merge
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: https://github.com/puiterwijk-gitops/clusters.git
        username: token
  data:
    - secretKey: password
      remoteRef:
        key: ocp_hub_config/gitops-pull-token
        property: token
