apiVersion: v1
kind: ConfigMap
metadata:
  name: config-puiterwijk-general
  namespace: rhdh
data:
  config-puiterwijk-general.yaml: |
    app:
      title: PUiterwijk Developer Hub
      baseUrl: https://devhub.puiterwijk.org
      routes:
        bindings:
          scaffolder.registerComponent: false
      support:
        url: "https://puiterwijk.org/"
        items:
          - title: "GitHub Org"
            icon: github
            links:
              - url: https://github.com/puiterwijk-gitops/
                title: "PUiterwijk GitOps"
    signInPage: oidc
    organization:
      name: PUiterwijk
    auth:
      environment: production
      session:
        secret: "${BACKEND_SECRET}"
      providers:
        oidc:
          production:
            metadataUrl: "https://sso.puiterwijk.org/realms/services"
            clientId: "${AUTH_OIDC_CLIENT_ID}"
            clientSecret: "${AUTH_OIDC_CLIENT_SECRET}"
            prompt: auto
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
                - resolver: emailMatchingUserEntityProfileEmail
        github:
          production:
            clientId: "${GITHUB_CLIENT_ID}"
            clientSecret: "${GITHUB_CLIENT_SECRET}"
    integrations:
      github:
        - host: "${GITHUB_HOST_DOMAIN}"
          apps:
            - appId: "${GITHUB_APP_ID}"
              allowedInstallationOwners: ['puiterwijk-gitops']
              clientId: "${GITHUB_CLIENT_ID}"
              clientSecret: "${GITHUB_CLIENT_SECRET}"
              webhookUrl: "${GITHUB_WEBHOOK_URL}"
              webhookSecret: "${GITHUB_WEBHOOK_SECRET}"
              privateKey: |
                ${GITHUB_PRIVATE_KEY_FILE}
    backend:
      baseUrl: https://devhub.puiterwijk.org
      cors:
        origin: https://devhub.puiterwijk.org
      auth:
        externalAccess:
          - type: legacy
            options:
              subject: legacy-default-config
              secret: "${LEGACY_BACKEND_SECRET}"
    permission:
      enabled: true
      rbac:
        policies-csv-file: /opt/app-root/src/rbac-policies.csv
        conditionalPoliciesFile: /opt/app-root/src/rbac-conditional-policies.yaml
        policyFileReload: true
        admin:
          users:
            - name: group:default/devhub-admins
    kubernetes:
      frontend:
        podDelete:
          enabled: true
      serviceLocatorMethod:
        type: 'catalogRelation'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: 'ocp-hub'
              title: "Hub Cluster"
              url: "https://kubernets.default.svc.cluster.local"
              authProvider: "serviceAccount"
              dashboardApp: openshift
              dashboardUrl: "https://console-openshift-console.apps.primary.ocp.puiterwijk.org/"
              caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
