apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: cloudflare-token
  namespace: acm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: cloudflare-token
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: cloudflare-token
