apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
spec:
  provider:
    vault:
      server: "https://vault.puiterwijk.org"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "ocp/${CLUSTER_NAME}"
          role: "cluster-secrets"
          serviceAccountRef:
            name: "cluster-secrets"
            namespace: "external-secrets"
