apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: sso
      mappingMethod: claim
      type: OpenID
      openID:
        issuer: https://sso.puiterwijk.org/realms/services
        clientID: openshift
        clientSecret:
          name: oidc-client-info
        extraScopes:
          - email
          - profile
          - groups
        claims:
          preferredUsername:
            - preferred_username
          name:
            - name
          email:
            - email
          groups:
            - groups
