apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-client-info
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: oidc-client-info
  data:
    - secretKey: clientId
      remoteRef:
        key: ocp/allclusters/oidc
        property: client_id
    - secretKey: clientSecret
      remoteRef:
        key: ocp/allclusters/oidc
        property: client_secret
