apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-client-info
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: oidc-client-info
    template:
      mergePolicy: Merge
      metadata:
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  data:
    - secretKey: clientSecret
      remoteRef:
        key: ocp/cluster/${CLUSTER_NAME}/oidc
        property: client_secret
