apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: rhacs
spec:
  monitoring:
    openShift:
      enabled: true
  network:
    policies: Enabled
  central:
    adminPasswordGenerationDisabled: false
    declarativeConfiguration:
      configMaps:
        - name: declarative-configurations
    exposure:
      route:
        enabled: true
        host: "acs.${SUB_DOMAIN}"
    telemetry:
      enabled: false
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
    scannerV4:
      db:
        persistence:
          persistentVolumeClaim:
            claimName: scanner-v4-db
