apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-configs
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/puiterwijk-gitops/cluster-config.git
        revision: HEAD
        directories:
          - path: overlays/*
  template:
    metadata:
      name: "vault-config-{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/puiterwijk-gitops/helm-charts.git
        targetRevision: HEAD
        path: vault-config/
        helm:
          valuesObject:
            clusterName: "{{ .path.basename }}"
      destination:
        name: in-cluster
        namespace: open-cluster-management
