apiVersion: v1
kind: ConfigMap
metadata:
  name: declarative-configuration
  namespace: rhacs
data:
  auth-provider-osauth: |
    name: openshift
    minimumRole: None
    uiEndpoint: acs.apps.primary.ocp.puiterwijk.org
    groups:
    - key: groups
      value: cluster-admins
      role: Admin
    openshift:
      enable: true
