apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-configs
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/puiterwijk-gitops/clusters.git
        revision: HEAD
        files:
          - path: "*.yaml"
  template:
    metadata:
      name: "vault-config-{{ .name }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/puiterwijk-gitops/helm-charts.git
        targetRevision: HEAD
        path: vault-config/
        helm:
          valuesObject:
            clusterName: "{{ .name }}"
            clusterDomain: "{{ .domain }}"
            clusterAcmName: "{{ .acm_name }}"
      destination:
        name: in-cluster
        namespace: open-cluster-management
      syncPolicy:
        automated:
          prune: true
